<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>IPScanner</AssemblyName>
    <RootNamespace>IPScanner</RootNamespace>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <Version>1.0.0</Version>
    <Product>IPZ IP Tarayıcı</Product>
    <ApplicationIcon>Resources\ipz.ico</ApplicationIcon>
    <Company>IPZ PROJE</Company>
    <Authors>Kutluhan</Authors>
    <Copyright>© Kutluhan – IPZ PROJE</Copyright>
    <InvariantGlobalization>false</InvariantGlobalization>
    <SatelliteResourceLanguages>tr;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\oui.txt.gz" LogicalName="IPScanner.oui.txt.gz" />
    <EmbeddedResource Include="Resources\ipz-logo-white.png" LogicalName="IPScanner.ipz-logo-white.png" />
  </ItemGroup>

</Project>
